export enum IngameDataEnum
{
  ArrowCharge,
  ArrowRainRuneSkill,
  AttackIncreaseAfterRevival,
  AttackPower,
  AttackSpeedModifier,
  AutoAbsorbsMeteorPotion,
  BarrageDamageReduction,
  BaseArmorStats,
  BaseAttackPower,
  BaseAttackSpeed,
  BaseCritChance,
  BaseCritDamage,
  BaseMaxHp,
  BaseRedHeartHealingValue,
  BossDamageModifier,
  BossDamageReduction,
  ChanceDevilEventAppearIncrease,
  CircleDamageBonus,
  CircleOrbDamageModifier,
  CircleOrbRuneSkill,
  CircleOrbRuneSkill2,
  CircleOrbRuneSkill3,
  CirclePulsesShrinkAndExpand,
  CircleRotateSpeed,
  CircleTrailDealDamage,
  CloseDistanceRange,
  CollisionDamageReduction,
  Combo,
  ComboAttackSpeedIncrease,
  ComboCritDamage,
  ComboCritRate,
  ComboDiagonalAttack,
  ComboDmgIncrease,
  ComboDoubleDamage,
  DamageReduction,
  DamageToPlayerModifier,
  DodgeChance,
  DoubleMeteorChance,
  DoubleStrike,
  ElementalDomainEffect,
  ElementalDomainEffectBuff,
  EpicOrHigherSkillObtainingChanceInValkyrieIncrease,
  ExpGainRate,
  ExplodeDamageModifier,
  ExplodeOnEnemy,
  ExtraMeteorSummonChanceOnPickupPotion,
  FireDamage,
  FireSpriteAttackSpeed,
  FireSpriteDmg,
  FireUpgrade,
  FlamePoisonSealFlame,
  FlamePoisonSealPoison,
  FlamePoisonSealReduceCd,
  FlamePoisonTocuhReduceCd,
  FlamePoisonTouchFlame,
  FlamePoisonTouchPoison,
  FlyingSwordBecomeDragonStrikeChance,
  FormingWebIfFireMoreThan4ProjectilesAtOnceChance,
  FrostThunderSealIce,
  FrostThunderSealIncreaseTarget,
  FrostThunderSealThunder,
  FrostThunderTouchBuff,
  FrostThunderTouchIce,
  FrostThunderTouchThunder,
  GiantMeteorSummonAfterSummon5Meteors,
  GoldObtainedIncrease,
  HealFullOnBossAppear,
  HealOnKillAmount,
  HealOnKillChance,
  HealOnLevelUpValue,
  HealingSpriteAttackSpeed,
  HealingSpriteAttackSpeedModifier,
  HealingSpriteDmg,
  HealingSpriteDmgModifier,
  HealingSpriteRuneSkill,
  IceDamage,
  IceEffect,
  IceSpriteAttackSpeed,
  IceSpriteDmg,
  IceUpgrade,
  IncreaseCircleSkillAppearChance,
  IncreaseElementalSkillAppearChance,
  IncreaseMainWeaponSkillAppearChance,
  IncreaseMeteorSkillAppearChance,
  IncreaseSpriteSkillAppearChance,
  IncreaseSwordStrikeSkillAppearChance,
  InvincibleFrameAfterHit,
  InvincibleOnTakingPotion,
  LandMineSpawnOnAttackChance,
  LaserCharge,
  LaserSpriteAttackSpeed,
  LaserSpriteDmg,
  LevelCapInPlaySession,
  LightningSpriteAttackSpeed,
  LightningSpriteDmg,
  LightwingArrowChance,
  Luck,
  MainWeaponDamageBonus,
  MainWeaponDamageModifier,
  MaxHpAddOnTakingHeart,
  MeteorChanceToBecomeGiant,
  MeteorDamage,
  MeteorDamageModifier,
  MeteorSplitEffect,
  MeteorSplitEffectBuff,
  MonsterDamageModifier,
  MonsterDamageReduction,
  MonsterKillMakeNextAttackExplode,
  MoveSpeed,
  PlayerDamageReduction,
  PlayerFrozenStatusImmuneTime,
  PoisonDamage,
  PoisonSpriteAttackSpeed,
  PoisonSpriteDmg,
  PoisonUpgrade,
  ProjectileBackward,
  ProjectileBounceWall,
  ProjectileDiagonal,
  ProjectileForwardAddition,
  ProjectilePenetration,
  ProjectileRapidShoot,
  ProjectileSize,
  ProjectileSplit,
  ProjectileTracking,
  ProjectileWallPenetration,
  RecoverHpWhenSummonMeteorAmount,
  RedHeartAddMaxHpChance,
  RedHeartHealModifier,
  ReduceHpLossInDevilEvent,
  ReviveCount,
  ReviveWithHalfHpChance,
  ReviveWithHalfHpCount,
  RingCharge,
  RingOfAgonyDamageEffect,
  RingOfAgonyRange,
  RingOfAgonySkill,
  RingOfAgonySkillBuff,
  RotatingCircleOrbNumber,
  RotatingOrbsFormAWeb,
  RouletteLandingOnValkyrieChanceIncrease,
  Shield,
  ShockDamage,
  ShockUpgrade,
  SpriteAttackSpeed,
  SpriteAttackSpeedModifier,
  SpriteAweEffect,
  SpriteAweEffect2,
  SpriteChanceToFire5FastShot,
  SpriteDamageBonus,
  SpriteDamageIncreaseEachExtraSprite,
  SpriteDamageModfier,
  SpriteKingAttackSpeed,
  SpriteKingDmg,
  StageCurrentExp,
  StarOfTimeDoubleSpawn,
  StarOfTimeMeteorSkill,
  StarOfTimeSkillCdReduction,
  StrikeDamageBonus,
  StrikeDamageModifer,
  StrikePotionRuneDoubleChance,
  StrikePotionRuneEffect,
  StrikePotionRuneEffectBuff,
  StrikeRicochetChance,
  Summon3MeteorsWhenDamaged,
  SummonMeteorChanceOnAttack,
  SummonMeteorOnKill,
  SuperRotatingCircleOrbNumber,
  SwordOfTimeCdReduction,
  SwordOfTimeDoubleSummon,
  SwordOfTimeSkill,
  SwordStrikeSplitEffect,
  SwordStrikeSplitEffectBuff,
  TriggerExplosionOnMonsterAfterDodge,
  CritGain3ComboPoint,
  StationaryDamageReduction,
  CloseRangeCritRateIncrease,
  CloseRangeCritDamageIncrease,
  DealDamageToMonsterInCloseRange,
  EnemiesTakeMoreDamageInCloseRange,
  MovingDamageReduction,
  NextAttackPlus1MultishotAfterCritChance,
  SkillRefreshTime,
  FirstSkillSelectionWhenStartSession,
  ScrollDropRate,
  GearDropRate,
  RuneDropRate,
  AngelRecoveryIncrease,
  RedHeartHealValueIncrease,
  HealOnLevelUpValueIncrease,
  EliteDamageModifier,
  EliteDamageReduction,
  // Add other attributes here
}

export class InGameData
{
  public static attributes = 
  {
    [IngameDataEnum.ArrowCharge]: false,
    [IngameDataEnum.ArrowRainRuneSkill]: false,
    [IngameDataEnum.AttackIncreaseAfterRevival]: 0,
    [IngameDataEnum.AttackPower]: 100,
    [IngameDataEnum.AttackSpeedModifier]: 100,
    [IngameDataEnum.AutoAbsorbsMeteorPotion]: false,
    [IngameDataEnum.BarrageDamageReduction]: 0,
    [IngameDataEnum.BaseArmorStats]: 0,
    [IngameDataEnum.BaseAttackPower]: 100,
    [IngameDataEnum.BaseAttackSpeed]: 1.5,
    [IngameDataEnum.BaseCritChance]: 0.02,
    [IngameDataEnum.BaseCritDamage]: 1.5,
    [IngameDataEnum.BaseMaxHp]: 300,
    [IngameDataEnum.BaseRedHeartHealingValue]: 25,
    [IngameDataEnum.BossDamageModifier]: 100,
    [IngameDataEnum.BossDamageReduction]: 0,
    [IngameDataEnum.ChanceDevilEventAppearIncrease]: 0,
    [IngameDataEnum.CircleDamageBonus]: 0,
    [IngameDataEnum.CircleOrbDamageModifier]: 100,
    [IngameDataEnum.CircleOrbRuneSkill]: false,
    [IngameDataEnum.CircleOrbRuneSkill2]: false,
    [IngameDataEnum.CircleOrbRuneSkill3]: false,
    [IngameDataEnum.CirclePulsesShrinkAndExpand]: false,
    [IngameDataEnum.CircleRotateSpeed]: 5,
    [IngameDataEnum.CircleTrailDealDamage]: false,
    [IngameDataEnum.CloseDistanceRange]: 5,
    [IngameDataEnum.CollisionDamageReduction]: 0,
    [IngameDataEnum.Combo]: 0,
    [IngameDataEnum.ComboAttackSpeedIncrease]: 0,
    [IngameDataEnum.ComboCritDamage]: false,
    [IngameDataEnum.ComboCritRate]: 0,
    [IngameDataEnum.ComboDiagonalAttack]: false,
    [IngameDataEnum.ComboDmgIncrease]: 0,
    [IngameDataEnum.ComboDoubleDamage]: false,
    [IngameDataEnum.DamageReduction]: 0,
    [IngameDataEnum.DamageToPlayerModifier]: 100,
    [IngameDataEnum.DodgeChance]: 0,
    [IngameDataEnum.DoubleMeteorChance]: false,
    [IngameDataEnum.DoubleStrike]: false,
    [IngameDataEnum.ElementalDomainEffect]: false,
    [IngameDataEnum.ElementalDomainEffectBuff]: false,
    [IngameDataEnum.EpicOrHigherSkillObtainingChanceInValkyrieIncrease]: 0,
    [IngameDataEnum.ExpGainRate]: 100,
    [IngameDataEnum.ExplodeDamageModifier]: 100,
    [IngameDataEnum.ExplodeOnEnemy]: false,
    [IngameDataEnum.ExtraMeteorSummonChanceOnPickupPotion]: 0,
    [IngameDataEnum.FireDamage]: 0,
    [IngameDataEnum.FireSpriteAttackSpeed]: 1,
    [IngameDataEnum.FireSpriteDmg]: 40,
    [IngameDataEnum.FireUpgrade]: false,
    [IngameDataEnum.FlamePoisonSealFlame]: false,
    [IngameDataEnum.FlamePoisonSealPoison]: false,
    [IngameDataEnum.FlamePoisonSealReduceCd]: false,
    [IngameDataEnum.FlamePoisonTocuhReduceCd]: false,
    [IngameDataEnum.FlamePoisonTouchFlame]: false,
    [IngameDataEnum.FlamePoisonTouchPoison]: false,
    [IngameDataEnum.FlyingSwordBecomeDragonStrikeChance]: 0,
    [IngameDataEnum.FormingWebIfFireMoreThan4ProjectilesAtOnceChance]: 0,
    [IngameDataEnum.FrostThunderSealIce]: false,
    [IngameDataEnum.FrostThunderSealIncreaseTarget]: false,
    [IngameDataEnum.FrostThunderSealThunder]: false,
    [IngameDataEnum.FrostThunderTouchBuff]: false,
    [IngameDataEnum.FrostThunderTouchIce]: false,
    [IngameDataEnum.FrostThunderTouchThunder]: false,
    [IngameDataEnum.GiantMeteorSummonAfterSummon5Meteors]: false,
    [IngameDataEnum.GoldObtainedIncrease]: 0,
    [IngameDataEnum.HealFullOnBossAppear]: false,
    [IngameDataEnum.HealOnKillAmount]: 10,
    [IngameDataEnum.HealOnKillChance]: 0,
    [IngameDataEnum.HealOnLevelUpValue]: 10,
    [IngameDataEnum.HealingSpriteAttackSpeed]: 1,
    [IngameDataEnum.HealingSpriteAttackSpeedModifier]: 100,
    [IngameDataEnum.HealingSpriteDmg]: 20,
    [IngameDataEnum.HealingSpriteDmgModifier]: 100,
    [IngameDataEnum.HealingSpriteRuneSkill]: false,
    [IngameDataEnum.IceDamage]: 0,
    [IngameDataEnum.IceEffect]: false,
    [IngameDataEnum.IceSpriteAttackSpeed]: 1,
    [IngameDataEnum.IceSpriteDmg]: 10,
    [IngameDataEnum.IceUpgrade]: false,
    [IngameDataEnum.IncreaseCircleSkillAppearChance]: 0,
    [IngameDataEnum.IncreaseElementalSkillAppearChance]: 0,
    [IngameDataEnum.IncreaseMainWeaponSkillAppearChance]: 0,
    [IngameDataEnum.IncreaseMeteorSkillAppearChance]: 0,
    [IngameDataEnum.IncreaseSpriteSkillAppearChance]: 0,
    [IngameDataEnum.IncreaseSwordStrikeSkillAppearChance]: 0,
    [IngameDataEnum.InvincibleFrameAfterHit]: 0.2,
    [IngameDataEnum.InvincibleOnTakingPotion]: false,
    [IngameDataEnum.LandMineSpawnOnAttackChance]: 0,
    [IngameDataEnum.LaserCharge]: false,
    [IngameDataEnum.LaserSpriteAttackSpeed]: 1,
    [IngameDataEnum.LaserSpriteDmg]: 50,
    [IngameDataEnum.LevelCapInPlaySession]: 10,
    [IngameDataEnum.LightningSpriteAttackSpeed]: 1,
    [IngameDataEnum.LightningSpriteDmg]: 30,
    [IngameDataEnum.LightwingArrowChance]: 0,
    [IngameDataEnum.Luck]: 0,
    [IngameDataEnum.MainWeaponDamageBonus]: 0,
    [IngameDataEnum.MainWeaponDamageModifier]: 100,
    [IngameDataEnum.MaxHpAddOnTakingHeart]: 0,
    [IngameDataEnum.MeteorChanceToBecomeGiant]: 0,
    [IngameDataEnum.MeteorDamage]: 100,
    [IngameDataEnum.MeteorDamageModifier]: 100,
    [IngameDataEnum.MeteorSplitEffect]: false,
    [IngameDataEnum.MeteorSplitEffectBuff]: false,
    [IngameDataEnum.MonsterDamageModifier]: 100,
    [IngameDataEnum.MonsterDamageReduction]: 0,
    [IngameDataEnum.MonsterKillMakeNextAttackExplode]: false,
    [IngameDataEnum.MoveSpeed]: 2,
    [IngameDataEnum.PlayerDamageReduction]: 0,
    [IngameDataEnum.PlayerFrozenStatusImmuneTime]: 10,
    [IngameDataEnum.PoisonDamage]: 0,
    [IngameDataEnum.PoisonSpriteAttackSpeed]: 1,
    [IngameDataEnum.PoisonSpriteDmg]: 50,
    [IngameDataEnum.PoisonUpgrade]: false,
    [IngameDataEnum.ProjectileBackward]: false,
    [IngameDataEnum.ProjectileBounceWall]: false,
    [IngameDataEnum.ProjectileDiagonal]: false,
    [IngameDataEnum.ProjectileForwardAddition]: 0,
    [IngameDataEnum.ProjectilePenetration]: false,
    [IngameDataEnum.ProjectileRapidShoot]: false,
    [IngameDataEnum.ProjectileSize]: 100,
    [IngameDataEnum.ProjectileSplit]: false,
    [IngameDataEnum.ProjectileTracking]: false,
    [IngameDataEnum.ProjectileWallPenetration]: false,
    [IngameDataEnum.RecoverHpWhenSummonMeteorAmount]: 0,
    [IngameDataEnum.RedHeartAddMaxHpChance]: 0,
    [IngameDataEnum.RedHeartHealModifier]: 100,
    [IngameDataEnum.ReduceHpLossInDevilEvent]: 0,
    [IngameDataEnum.ReviveCount]: 0,
    [IngameDataEnum.ReviveWithHalfHpChance]: 0,
    [IngameDataEnum.ReviveWithHalfHpCount]: 0,
    [IngameDataEnum.RingCharge]: false,
    [IngameDataEnum.RingOfAgonyDamageEffect]: false,
    [IngameDataEnum.RingOfAgonyRange]: 3,
    [IngameDataEnum.RingOfAgonySkill]: false,
    [IngameDataEnum.RingOfAgonySkillBuff]: false,
    [IngameDataEnum.RotatingCircleOrbNumber]: 2,
    [IngameDataEnum.RotatingOrbsFormAWeb]: false,
    [IngameDataEnum.RouletteLandingOnValkyrieChanceIncrease]: 0,
    [IngameDataEnum.Shield]: false,
    [IngameDataEnum.ShockDamage]: 0,
    [IngameDataEnum.ShockUpgrade]: false,
    [IngameDataEnum.SpriteAttackSpeed]: 0.5,
    [IngameDataEnum.SpriteAttackSpeedModifier]: 100,
    [IngameDataEnum.SpriteAweEffect]: false,
    [IngameDataEnum.SpriteAweEffect2]: false,
    [IngameDataEnum.SpriteChanceToFire5FastShot]: 0,
    [IngameDataEnum.SpriteDamageBonus]: 0,
    [IngameDataEnum.SpriteDamageIncreaseEachExtraSprite]: 0,
    [IngameDataEnum.SpriteDamageModfier]: 100,
    [IngameDataEnum.SpriteKingAttackSpeed]: 1,
    [IngameDataEnum.SpriteKingDmg]: 60,
    [IngameDataEnum.StageCurrentExp]: 0,
    [IngameDataEnum.StarOfTimeDoubleSpawn]: false,
    [IngameDataEnum.StarOfTimeMeteorSkill]: false,
    [IngameDataEnum.StarOfTimeSkillCdReduction]: false,
    [IngameDataEnum.StrikeDamageBonus]: 0,
    [IngameDataEnum.StrikeDamageModifer]: 100,
    [IngameDataEnum.StrikePotionRuneDoubleChance]: false,
    [IngameDataEnum.StrikePotionRuneEffect]: false,
    [IngameDataEnum.StrikePotionRuneEffectBuff]: false,
    [IngameDataEnum.StrikeRicochetChance]: 0,
    [IngameDataEnum.Summon3MeteorsWhenDamaged]: false,
    [IngameDataEnum.SummonMeteorChanceOnAttack]: 0,
    [IngameDataEnum.SummonMeteorOnKill]: false,
    [IngameDataEnum.SuperRotatingCircleOrbNumber]: 4,
    [IngameDataEnum.SwordOfTimeCdReduction]: false,
    [IngameDataEnum.SwordOfTimeDoubleSummon]: false,
    [IngameDataEnum.SwordOfTimeSkill]: false,
    [IngameDataEnum.SwordStrikeSplitEffect]: false,
    [IngameDataEnum.SwordStrikeSplitEffectBuff]: false,
    [IngameDataEnum.TriggerExplosionOnMonsterAfterDodge]: false,
    [IngameDataEnum.CritGain3ComboPoint]: false,
    [IngameDataEnum.StationaryDamageReduction]: 0,
    [IngameDataEnum.CloseRangeCritRateIncrease]: 0,
    [IngameDataEnum.CloseRangeCritDamageIncrease]: 0,
    [IngameDataEnum.DealDamageToMonsterInCloseRange]: 0,
    [IngameDataEnum.EnemiesTakeMoreDamageInCloseRange]: 0,
    [IngameDataEnum.MovingDamageReduction]: 0,
    [IngameDataEnum.NextAttackPlus1MultishotAfterCritChance]: 0,
    [IngameDataEnum.SkillRefreshTime]: 0,
    [IngameDataEnum.FirstSkillSelectionWhenStartSession]: false,
    [IngameDataEnum.ScrollDropRate]: 0,
    [IngameDataEnum.GearDropRate]: 0,
    [IngameDataEnum.RuneDropRate]: 0,
    [IngameDataEnum.AngelRecoveryIncrease]: 0,
    [IngameDataEnum.RedHeartHealValueIncrease]: 0,
    [IngameDataEnum.HealOnLevelUpValueIncrease]: 0,
    [IngameDataEnum.EliteDamageModifier]: 100,
    [IngameDataEnum.EliteDamageReduction]: 0,
    // Add other attributes here
  };

  // constructor()
  // {
  //   SetDefaultData();
  // }

  public static GetAttribute<K extends IngameDataEnum>(key: K): typeof InGameData.attributes[K]
  {
    return InGameData.attributes[key];
  }

  public static SetAttribute<K extends IngameDataEnum>(key: K, value: any): void
  {
    InGameData.attributes[key] = value;
  }

  public static SetDefaultData()
  {
    InGameData.attributes = PlayerDataDefault;
  }
}

const PlayerDataDefault = 
{
  [IngameDataEnum.ArrowCharge]: false,
  [IngameDataEnum.ArrowRainRuneSkill]: false,
  [IngameDataEnum.AttackIncreaseAfterRevival]: 0,
  [IngameDataEnum.AttackPower]: 100,
  [IngameDataEnum.AttackSpeedModifier]: 100,
  [IngameDataEnum.AutoAbsorbsMeteorPotion]: false,
  [IngameDataEnum.BarrageDamageReduction]: 0,
  [IngameDataEnum.BaseArmorStats]: 0,
  [IngameDataEnum.BaseAttackPower]: 100,
  [IngameDataEnum.BaseAttackSpeed]: 1.5,
  [IngameDataEnum.BaseCritChance]: 0.02,
  [IngameDataEnum.BaseCritDamage]: 1.5,
  [IngameDataEnum.BaseMaxHp]: 300,
  [IngameDataEnum.BaseRedHeartHealingValue]: 25,
  [IngameDataEnum.BossDamageModifier]: 100,
  [IngameDataEnum.BossDamageReduction]: 0,
  [IngameDataEnum.ChanceDevilEventAppearIncrease]: 0,
  [IngameDataEnum.CircleDamageBonus]: 0,
  [IngameDataEnum.CircleOrbDamageModifier]: 100,
  [IngameDataEnum.CircleOrbRuneSkill]: false,
  [IngameDataEnum.CircleOrbRuneSkill2]: false,
  [IngameDataEnum.CircleOrbRuneSkill3]: false,
  [IngameDataEnum.CirclePulsesShrinkAndExpand]: false,
  [IngameDataEnum.CircleRotateSpeed]: 5,
  [IngameDataEnum.CircleTrailDealDamage]: false,
  [IngameDataEnum.CloseDistanceRange]: 5,
  [IngameDataEnum.CollisionDamageReduction]: 0,
  [IngameDataEnum.Combo]: 0,
  [IngameDataEnum.ComboAttackSpeedIncrease]: 0,
  [IngameDataEnum.ComboCritDamage]: false,
  [IngameDataEnum.ComboCritRate]: 0,
  [IngameDataEnum.ComboDiagonalAttack]: false,
  [IngameDataEnum.ComboDmgIncrease]: 0,
  [IngameDataEnum.ComboDoubleDamage]: false,
  [IngameDataEnum.DamageReduction]: 0,
  [IngameDataEnum.DamageToPlayerModifier]: 100,
  [IngameDataEnum.DodgeChance]: 0,
  [IngameDataEnum.DoubleMeteorChance]: false,
  [IngameDataEnum.DoubleStrike]: false,
  [IngameDataEnum.ElementalDomainEffect]: false,
  [IngameDataEnum.ElementalDomainEffectBuff]: false,
  [IngameDataEnum.EpicOrHigherSkillObtainingChanceInValkyrieIncrease]: 0,
  [IngameDataEnum.ExpGainRate]: 100,
  [IngameDataEnum.ExplodeDamageModifier]: 100,
  [IngameDataEnum.ExplodeOnEnemy]: false,
  [IngameDataEnum.ExtraMeteorSummonChanceOnPickupPotion]: 0,
  [IngameDataEnum.FireDamage]: 0,
  [IngameDataEnum.FireSpriteAttackSpeed]: 1,
  [IngameDataEnum.FireSpriteDmg]: 40,
  [IngameDataEnum.FireUpgrade]: false,
  [IngameDataEnum.FlamePoisonSealFlame]: false,
  [IngameDataEnum.FlamePoisonSealPoison]: false,
  [IngameDataEnum.FlamePoisonSealReduceCd]: false,
  [IngameDataEnum.FlamePoisonTocuhReduceCd]: false,
  [IngameDataEnum.FlamePoisonTouchFlame]: false,
  [IngameDataEnum.FlamePoisonTouchPoison]: false,
  [IngameDataEnum.FlyingSwordBecomeDragonStrikeChance]: 0,
  [IngameDataEnum.FormingWebIfFireMoreThan4ProjectilesAtOnceChance]: 0,
  [IngameDataEnum.FrostThunderSealIce]: false,
  [IngameDataEnum.FrostThunderSealIncreaseTarget]: false,
  [IngameDataEnum.FrostThunderSealThunder]: false,
  [IngameDataEnum.FrostThunderTouchBuff]: false,
  [IngameDataEnum.FrostThunderTouchIce]: false,
  [IngameDataEnum.FrostThunderTouchThunder]: false,
  [IngameDataEnum.GiantMeteorSummonAfterSummon5Meteors]: false,
  [IngameDataEnum.GoldObtainedIncrease]: 0,
  [IngameDataEnum.HealFullOnBossAppear]: false,
  [IngameDataEnum.HealOnKillAmount]: 10,
  [IngameDataEnum.HealOnKillChance]: 0,
  [IngameDataEnum.HealOnLevelUpValue]: 10,
  [IngameDataEnum.HealingSpriteAttackSpeed]: 1,
  [IngameDataEnum.HealingSpriteAttackSpeedModifier]: 100,
  [IngameDataEnum.HealingSpriteDmg]: 20,
  [IngameDataEnum.HealingSpriteDmgModifier]: 100,
  [IngameDataEnum.HealingSpriteRuneSkill]: false,
  [IngameDataEnum.IceDamage]: 0,
  [IngameDataEnum.IceEffect]: false,
  [IngameDataEnum.IceSpriteAttackSpeed]: 1,
  [IngameDataEnum.IceSpriteDmg]: 10,
  [IngameDataEnum.IceUpgrade]: false,
  [IngameDataEnum.IncreaseCircleSkillAppearChance]: 0,
  [IngameDataEnum.IncreaseElementalSkillAppearChance]: 0,
  [IngameDataEnum.IncreaseMainWeaponSkillAppearChance]: 0,
  [IngameDataEnum.IncreaseMeteorSkillAppearChance]: 0,
  [IngameDataEnum.IncreaseSpriteSkillAppearChance]: 0,
  [IngameDataEnum.IncreaseSwordStrikeSkillAppearChance]: 0,
  [IngameDataEnum.InvincibleFrameAfterHit]: 0.2,
  [IngameDataEnum.InvincibleOnTakingPotion]: false,
  [IngameDataEnum.LandMineSpawnOnAttackChance]: 0,
  [IngameDataEnum.LaserCharge]: false,
  [IngameDataEnum.LaserSpriteAttackSpeed]: 1,
  [IngameDataEnum.LaserSpriteDmg]: 50,
  [IngameDataEnum.LevelCapInPlaySession]: 10,
  [IngameDataEnum.LightningSpriteAttackSpeed]: 1,
  [IngameDataEnum.LightningSpriteDmg]: 30,
  [IngameDataEnum.LightwingArrowChance]: 0,
  [IngameDataEnum.Luck]: 0,
  [IngameDataEnum.MainWeaponDamageBonus]: 0,
  [IngameDataEnum.MainWeaponDamageModifier]: 100,
  [IngameDataEnum.MaxHpAddOnTakingHeart]: 0,
  [IngameDataEnum.MeteorChanceToBecomeGiant]: 0,
  [IngameDataEnum.MeteorDamage]: 100,
  [IngameDataEnum.MeteorDamageModifier]: 100,
  [IngameDataEnum.MeteorSplitEffect]: false,
  [IngameDataEnum.MeteorSplitEffectBuff]: false,
  [IngameDataEnum.MonsterDamageModifier]: 100,
  [IngameDataEnum.MonsterDamageReduction]: 0,
  [IngameDataEnum.MonsterKillMakeNextAttackExplode]: false,
  [IngameDataEnum.MoveSpeed]: 2,
  [IngameDataEnum.PlayerDamageReduction]: 0,
  [IngameDataEnum.PlayerFrozenStatusImmuneTime]: 10,
  [IngameDataEnum.PoisonDamage]: 0,
  [IngameDataEnum.PoisonSpriteAttackSpeed]: 1,
  [IngameDataEnum.PoisonSpriteDmg]: 50,
  [IngameDataEnum.PoisonUpgrade]: false,
  [IngameDataEnum.ProjectileBackward]: false,
  [IngameDataEnum.ProjectileBounceWall]: false,
  [IngameDataEnum.ProjectileDiagonal]: false,
  [IngameDataEnum.ProjectileForwardAddition]: 0,
  [IngameDataEnum.ProjectilePenetration]: false,
  [IngameDataEnum.ProjectileRapidShoot]: false,
  [IngameDataEnum.ProjectileSize]: 100,
  [IngameDataEnum.ProjectileSplit]: false,
  [IngameDataEnum.ProjectileTracking]: false,
  [IngameDataEnum.ProjectileWallPenetration]: false,
  [IngameDataEnum.RecoverHpWhenSummonMeteorAmount]: 0,
  [IngameDataEnum.RedHeartAddMaxHpChance]: 0,
  [IngameDataEnum.RedHeartHealModifier]: 100,
  [IngameDataEnum.ReduceHpLossInDevilEvent]: 0,
  [IngameDataEnum.ReviveCount]: 0,
  [IngameDataEnum.ReviveWithHalfHpChance]: 0,
  [IngameDataEnum.ReviveWithHalfHpCount]: 0,
  [IngameDataEnum.RingCharge]: false,
  [IngameDataEnum.RingOfAgonyDamageEffect]: false,
  [IngameDataEnum.RingOfAgonyRange]: 3,
  [IngameDataEnum.RingOfAgonySkill]: false,
  [IngameDataEnum.RingOfAgonySkillBuff]: false,
  [IngameDataEnum.RotatingCircleOrbNumber]: 2,
  [IngameDataEnum.RotatingOrbsFormAWeb]: false,
  [IngameDataEnum.RouletteLandingOnValkyrieChanceIncrease]: 0,
  [IngameDataEnum.Shield]: false,
  [IngameDataEnum.ShockDamage]: 0,
  [IngameDataEnum.ShockUpgrade]: false,
  [IngameDataEnum.SpriteAttackSpeed]: 0.5,
  [IngameDataEnum.SpriteAttackSpeedModifier]: 100,
  [IngameDataEnum.SpriteAweEffect]: false,
  [IngameDataEnum.SpriteAweEffect2]: false,
  [IngameDataEnum.SpriteChanceToFire5FastShot]: 0,
  [IngameDataEnum.SpriteDamageBonus]: 0,
  [IngameDataEnum.SpriteDamageIncreaseEachExtraSprite]: 0,
  [IngameDataEnum.SpriteDamageModfier]: 100,
  [IngameDataEnum.SpriteKingAttackSpeed]: 1,
  [IngameDataEnum.SpriteKingDmg]: 60,
  [IngameDataEnum.StageCurrentExp]: 0,
  [IngameDataEnum.StarOfTimeDoubleSpawn]: false,
  [IngameDataEnum.StarOfTimeMeteorSkill]: false,
  [IngameDataEnum.StarOfTimeSkillCdReduction]: false,
  [IngameDataEnum.StrikeDamageBonus]: 0,
  [IngameDataEnum.StrikeDamageModifer]: 100,
  [IngameDataEnum.StrikePotionRuneDoubleChance]: false,
  [IngameDataEnum.StrikePotionRuneEffect]: false,
  [IngameDataEnum.StrikePotionRuneEffectBuff]: false,
  [IngameDataEnum.StrikeRicochetChance]: 0,
  [IngameDataEnum.Summon3MeteorsWhenDamaged]: false,
  [IngameDataEnum.SummonMeteorChanceOnAttack]: 0,
  [IngameDataEnum.SummonMeteorOnKill]: false,
  [IngameDataEnum.SuperRotatingCircleOrbNumber]: 4,
  [IngameDataEnum.SwordOfTimeCdReduction]: false,
  [IngameDataEnum.SwordOfTimeDoubleSummon]: false,
  [IngameDataEnum.SwordOfTimeSkill]: false,
  [IngameDataEnum.SwordStrikeSplitEffect]: false,
  [IngameDataEnum.SwordStrikeSplitEffectBuff]: false,
  [IngameDataEnum.TriggerExplosionOnMonsterAfterDodge]: false,
  [IngameDataEnum.CritGain3ComboPoint]: false,
  [IngameDataEnum.StationaryDamageReduction]: 0,
  [IngameDataEnum.CloseRangeCritRateIncrease]: 0,
  [IngameDataEnum.CloseRangeCritDamageIncrease]: 0,
  [IngameDataEnum.DealDamageToMonsterInCloseRange]: 0,
  [IngameDataEnum.EnemiesTakeMoreDamageInCloseRange]: 0,
  [IngameDataEnum.MovingDamageReduction]: 0,
  [IngameDataEnum.NextAttackPlus1MultishotAfterCritChance]: 0,
  [IngameDataEnum.SkillRefreshTime]: 0,
  [IngameDataEnum.FirstSkillSelectionWhenStartSession]: false,
  [IngameDataEnum.ScrollDropRate]: 0,
  [IngameDataEnum.GearDropRate]: 0,
  [IngameDataEnum.RuneDropRate]: 0,
  [IngameDataEnum.AngelRecoveryIncrease]: 0,
  [IngameDataEnum.RedHeartHealValueIncrease]: 0,
  [IngameDataEnum.HealOnLevelUpValueIncrease]: 0,
  [IngameDataEnum.EliteDamageModifier]: 100,
  [IngameDataEnum.EliteDamageReduction]: 0,
};